#nb_epochs: 100
#heads : 2
#batch_size : 64
#list_num_layers : [8, 12]
#list_embed_size : [16, 32]
#list_forward_expansion : [4]
#list_dropout : [0.1]

gpt :
  nb_epochs: 500
  heads : 4
  batch_size : 64
  list_num_layers : [4, 8, 12]
  list_embed_size : [16, 32]
  list_forward_expansion : [4]
  list_dropout : [0.1]
  list_hidden_dim : [512]

lstm:
  nb_epochs: 500
  batch_size : 256
  list_num_layers : [4, 8, 12]
  list_embed_size : [16, 32]
  list_dropout : [0.1]
  list_hidden_dim : [512]

#gpt :
#  nb_epochs: 1
#  heads : 2
#  batch_size : 256
#  list_num_layers : [4]
#  list_embed_size : [4]
#  list_forward_expansion : [4]
#  list_dropout : [0.1]
#  list_hidden_dim : [256]
#
#lstm:
#  nb_epochs: 1
#  batch_size : 256
#  list_num_layers : [4]
#  list_embed_size : [4]
#  list_dropout : [0.1]
#  list_hidden_dim : [128]